### ISSUE TITLE
Solc 0.6.x, both downloaded and default, fail

### ISSUE THREAD

**Issue by charlescrain** [f-o-a-m/chanterelle#123]
UPDATE:

Even worse, the downloaded [c++ wrapped in JS verison: soljson](https://ethereum.github.io/solc-bin/bin/list.json) for 0.6.x acts differently than the solc-js version 0.6.x. The way to use different ones is to install solc-js 0.6.x into package.json and use default solc in chanterelle.json. The error below from using solc-js 0.6.x. 

----

https://github.com/ethereum/solc-js/tree/v0.6.1#high-level-api

Note: 
> It also accepts an optional set of callback functions, which include the import and the smtSolver callbacks. Starting 0.6.0 it only accepts an object in place of the callback to supply the callbacks.

This is related to https://github.com/f-o-a-m/purescript-solc/issues/5

**Comment by iostat** [comment]
Going to close this in favor of the `purescript-solc` issue.

long and short of it though:
* are you using the latest Chanterelle? (`v4.1.0` released two weeks ago was made to fix this very issue)
* if you updated a system-wide chanterelle (i.e. `npm install --global chanterelle@4.1.0`), did you run `chanterelle global-postinstall` after doing so?
* is the `solc` in your `package.json` `>= 0.6`? v0.6.2 is OpenZeppelin's current minimum solidity version. The solcjs wrapper is... weird. You're almost always better off using a equal or newer `solc` in your `package.json` than your chanterelle.json `solc-version`.
* If you changed the version of `solc`, did you `rm -rf node_modules/solc` before doing `npm install`? npm is... weird.

**Comment by iostat** [comment]
Actually, changed my mind, gonna close the purescript-solc issue in favor of this issue. It seems more like a chanterelle version + node paths issue than a purescript-solc

**Comment by iostat** [comment]
Gonna close this since latest changes seem to work fine with 0.8
