### ISSUE TITLE
When certain tests fail, they time out

### ISSUE THREAD

**Issue by kejace** [f-o-a-m/chanterelle#5]
For example a result of a transaction like this:

![image](https://user-images.githubusercontent.com/586216/37996619-4b06f066-31e6-11e8-82cb-7f3f897514cc.png)

seems to cause a timeout. Possibly this is because we're not parsing events relating to contract error.

![image](https://user-images.githubusercontent.com/586216/37996691-84e79a38-31e6-11e8-8589-673b776e1e5e.png)

Above could be triggered at https://github.com/f-o-a-m/chanterelle/blob/master/test/Spec/ParkingAuthoritySpec.purs#L99 for example by changing `accountIndex` to `0` instead of `2`. The point is that this errors out _inside_ the contract body but we're unable to even know that the transaction failed.

**Comment by blinky3713** [comment]
we can make a combinator to poll tx receipts and then throw an error in the main thread if the tx receipt indicates a failure

**Comment by blinky3713** [comment]
no more tests in this repo, moved to parking-dao
