### ISSUE TITLE
Explore a MonadPar instance for DeployM

### ISSUE THREAD

**Issue by iostat** [f-o-a-m/chanterelle#71]
There are some cases where deployment times can be significantly reduced by parallelizing the creation transaction and waiting for its receipt, especially when deploying contracts that don't take any arguments and libraries (see also, #70).

Being able to do something `parTraverse deployContract [lib1, lib2, noArg1, noArg2]` could potentially speed this up

**Comment by blinky3713** [comment]
you can pretty much copy paste the data defs and instances [here](https://github.com/f-o-a-m/purescript-web3/blob/master/src/Network/Ethereum/Web3/Types/Types.purs#L365)
