### ISSUE TITLE
Exit with non-zero on failures

### ISSUE THREAD

**Issue by iostat** [f-o-a-m/chanterelle#84]
Title kinda says it all. Most applications exit with a code other than zero when they experience failures (e.g., compiler error, deploy error). Chanterelle doesn't, but it should in order to be more readily integrated into Makefiles, CI pipelines, etc.

Should be fairly trivial to implement in the CLI foundation we have, and perhaps it's worth updating the compile and deploy script examples in the docs to exit with nonzero when failures are encountered

**Comment by safareli** [comment]
closed via  #89
