### ISSUE TITLE
make compile-contracts error

### ISSUE THREAD

**Issue by debragail** [f-o-a-m/chanterelle#93]
`Debras-MBP:parking-dao 0PHE1IA$ make compile-contracts`
`pulp build --src-path compile -m Compile --to compile.js && node compile.js --log-level info; rm compile.js`
`* Building project in /Users/0PHE1IA/foam/parking-dao`
`Error found:
at bower_components/purescript-pipes/src/Pipes/Internal.purs line 56, column 1 - line 56, column 1`

  `Unable to parse module:
  expecting indentation past column 1`

`See https://github.com/purescript/documentation/blob/master/errors/ErrorParsingModule.md for more information,
or to contribute content related to this error.`

`* ERROR: Subcommand terminated with exit code 1
rm: compile.js: No such file or directory
make: *** [compile-contracts] Error 1`

**Comment by blinky3713** [comment]
can you repost this in the parking dao project, it seems like this is a build error
